apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: mohan14242/fastapi:3.0
        ports:
        - containerPort: 8000
--- 
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80        # Port on which the service will be exposed
      targetPort: 8000
      nodePort: 30007
  type: NodePort  # Change to NodePort or ClusterIP as needed
